export {default as Header} from './Header & Footer/Header'
export {default as Home} from './Home/Home'
export {default as Products} from './Products & Shopping Cart/Products'
export {default as ShoppingCart} from './Products & Shopping Cart/ShoppingCart'
export {default as Checkout} from './CheckoutForm/Checkout/Checkout'
export {default as SingUp} from './Sing Up & Sing In/SingUp'
export {default as SingIn} from './Sing Up & Sing In/SingIn'
export {default as Footer} from './Header & Footer/Footer'
export {default as ProductRequest} from './Product Request/ProductRequest'

export {default as ComputersElectronics} from './Categories/Computers&Electronics'
export {default as SmartHome} from './Categories/SmartHome'
export {default as BooksMovies} from './Categories/Books&Movies'
export {default as Fashion} from './Categories/Fashion'
export {default as CosmeticsPersonalCare} from './Categories/Cosmetics&PersonalCare'