export {default as Header} from './Header & Footer/Header'
export {default as Home} from './Home/Home'
export {default as Products} from './Products & Shopping Cart/Products'
export {default as SingUp} from './Sing Up & Sing In/SingUp'
export {default as SingIn} from './Sing Up & Sing In/SingIn'
export {default as Footer} from './Header & Footer/Footer'

export {default as Computers_Electronics} from './Categories/Computers_Electronics'
export {default as SmartHome} from './Categories/SmartHome'
export {default as Books_Movies} from './Categories/Books_Movies'
export {default as Fashion} from './Categories/Fashion'
export {default as Cosmetics_PersonalCare} from './Categories/Cosmetics_PersonalCare'